20240818 ec crypto
programatik29/axum-server pull request #143
Opened 2024-08-18 03:59 UTC by Firstyear

Fixes #142 - allows usage of EC and PKCS1 keys.

2024-08-20 15:23 UTC, daxpedda requested changes
Could you add a changelog entry as well?

2024-08-21 00:22 UTC, Firstyear commented
@daxpedda Done, I hope that helps :)

2024-08-21 14:43 UTC, daxpedda commented on CHANGELOG.md
> +- **added**: Support `Pkcs1` and `Sec1` private keys with rustls.
```suggestion
- **added**: Support reading PKCS\#1 and SEC1 private keys with Rustls.
```

2024-08-21 14:46 UTC, merged

2024-08-21 23:08 UTC, Firstyear commented
Happy to help :)